Name:           ros-indigo-urdf-traverser
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS urdf_traverser package

Group:          Development/Libraries
License:        BSD (3-clause)
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-baselib-binding
Requires:       ros-indigo-eigen-conversions
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-roslint
Requires:       ros-indigo-urdf
BuildRequires:  ros-indigo-baselib-binding
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-eigen-conversions
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-roslint
BuildRequires:  ros-indigo-urdf

%description
Urdf traverser (C++) which provides functions to traverse the URDF and
convenience functions to access the URDF model.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sat Jan 06 2018 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.2-0
- Autogenerated by Bloom

* Sat Aug 06 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.1-0
- Autogenerated by Bloom

* Tue Jun 07 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

* Mon Jun 06 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.4-0
- Autogenerated by Bloom

* Sat Jun 04 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.3-0
- Autogenerated by Bloom

* Tue May 31 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 0.0.2-0
- Autogenerated by Bloom

